apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name}}
  namespace: {{ .Values.namespace}}
spec:
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{.Values.service.name}}
            port:
              number: 8281
        path: /api/data-exploration-service
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{.Values.service.name}}
            port:
              number: 8281
        path: /swagger/data-exploration-service
        pathType: ImplementationSpecific