apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name}}
  namespace: {{ .Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8133
        path: /api/configuration-center
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8133
        path: /swagger/configuration-center
        pathType: ImplementationSpecific
